name: example-sage
recipe: wordpress
proxy:
  appserver_nginx:
    - example-sage.lndo.site
  theme:
    - localhost:3009
#    - localhost:3001
config:
  php: '8.1'
  webroot: wordpress
  via: nginx
  database: 'mysql:5.7'
  xdebug: true
services:
  theme:
    type: node
    scanner: false
    services:
      ports:
        - 3009:3009
#        - 3001:3001
tooling:
  yarn:
    service: theme
  npm:
    service: theme