# .lando.yml
name: example
recipe: wordpress
config:
  php: '8.2'
  via: nginx
  webroot: web
# webroot: wordpress
  database: 'mysql:5.7'
  xdebug: true
proxy:
  appserver_nginx:
    - example.lndo.site # default
    # - example.test # for testing  
  phpmyadmin:
    - pma.example.lndo.site # default
    # - pma.example.test # for testing
  mailhog:
    - mail.example.lndo.site # default
    # - mail.example.test # for testing
services:
  database:
    type: 'mysql:5.7'
    portforward: 3306
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
      - appserver_nginx
  dev:
    type: node:20
    # overrides:
    #   ports:
    #     - 3000:3000
tooling:
  npm:
    service: dev
  yarn:
    service: dev
excludes:
  - vendor
  - node_modules